name: zed
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #BLoC-based state management for Flutter.
  flutter_bloc: ^8.1.4

  #Core BLoC package for Flutter state management.
  bloc: ^8.1.3

  # Firebase Core SDK for Flutter Firebase integration.
  firebase_core: ^2.24.2

  # Rive (formerly Flare) for Flutter animations.
  rive: ^0.12.4

  #Code generation for immutable classes in Dart.
  freezed_annotation: ^2.4.1

  # Firebase Authentication for Flutter Firebase integration.
  firebase_auth: ^4.16.0

  # Lottie for Flutter animations.
  lottie: ^2.7.0
  
  # Google Fonts package for Flutter.
  google_fonts: 6.1.0

  #Dart service locator for Flutter.
  get_it: ^7.6.7
  google_sign_in: ^6.1.6
  flutter_staggered_grid_view: ^0.7.0
  auto_size_text: ^3.0.0
  cloud_firestore: ^4.14.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  # Flutter Lints for enforcing best practices in Flutter code.
  flutter_lints: ^2.0.0

  # Build Runner for running code generation tasks.
  build_runner: ^2.4.8

  # Freezed for generating boilerplate code for immutable classes.
  freezed: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/